### ISSUE TITLE
MMLgui does not work in WINE on macOS

### ISSUE THREAD

**Issue by rhythmparker** [superctr/mmlgui#10]
As the title suggests, I cannot get MMLgui to run in macOS on WINE. I have tried to run it on macOS Mojave as well as macOS Big Sur. They both exit with a code that says:
`Glfw Error 65543: WGL: Failed to create OpenGL context`
I will add a log file below from WINE, if that's any use.
[wine.log](https://github.com/superctr/mmlgui/files/12066067/wine.log)

**Comment by superctr** [comment]
This doesn't seem like an issue with mmlgui, and it's also a platform I don't use so I can't help you with this. My only suggestion is that you build it from the source code instead of running the wine binary.
