### ISSUE TITLE
Weird behavior when using tab instead of space

### ISSUE THREAD

**Issue by pedipanol** [superctr/mmlgui#3]
Thought I'd report this, I normally use Tab for separating the channel indicator from the MML quickly, but when I use it anywhere on mmlgui it makes the cursor stay behind the current playing note until it goes to a new line that doesn't use tab, the sound plays just fine tho.

![image](https://user-images.githubusercontent.com/26771164/91796831-83dd7680-ebf7-11ea-9007-79bcb369288e.png)

I imagine it's treating it as a normal space

**Comment by superctr** [comment]
Tabs are not counted properly when calculating the column position and it's
a known issue.

Each MML command has an internal reference to the place in the file where
it was defined, this is used for both displaying compilation errors and
tracing notes during playback. The MML compiler has no idea about the tab
width so it for now it will always count a tab as a single space.

Den tis 1 sep. 2020 07:05pedipanol <notifications@github.com> skrev:

**Comment by superctr** [comment]
I also fixed a bug in the text editor where pressing backspace after inserting a tab caused the cursor to skip too many positions.
